star-toy/polling-backend

src/main/java/com/startoy/pollhub/adapter/controller/VoteController.java, src/main/java/com/startoy/pollhub/adapter/repository/VoteRepository.java, src/main/java/com/startoy/pollhub/domain/Vote.java, src/main/java/com/startoy/pollhub/usecase/VoteService.java
- ### ph_vote 테이블 추가
- ### ip기반 비회원 투표 기능 개발
=> ✨Feat: ip기반 비회원 투표 기능 추가

src/main/java/com/startoy/pollhub/adapter/controller/PollController.java, src/main/java/com/startoy/pollhub/adapter/controller/PollOptionController.java, src/main/java/com/startoy/pollhub/adapter/controller/PostController.java, src/main/java/com/startoy/pollhub/adapter/controller/VoteController.java
- ### Controller api 주소 수정
- /api/polls -> /v1/polls
=> ♻️Refactor : API 주소를 v1으로 변경 (/api/polls -> /v1/polls)

src/main/java/com/startoy/pollhub/adapter/controller/PollController.java, src/main/java/com/startoy/pollhub/adapter/controller/PollOptionController.java, src/main/java/com/startoy/pollhub/adapter/controller/PostController.java, src/main/java/com/startoy/pollhub/adapter/controller/VoteController.java, src/main/java/com/startoy/pollhub/adapter/repository/VoteRepository.java, src/main/java/com/startoy/pollhub/usecase/PollOptionService.java, src/main/java/com/startoy/pollhub/usecase/PollService.java, src/main/java/com/startoy/pollhub/usecase/PostService.java, src/main/java/com/startoy/pollhub/usecase/VoteService.java
=> ♻️Refactor:  @RequiredArgsConstructor 적용

src/main/java/com/startoy/pollhub/adapter/controller/PollController.java, src/main/java/com/startoy/pollhub/adapter/controller/PollOptionController.java, src/main/java/com/startoy/pollhub/adapter/controller/PostController.java, src/main/java/com/startoy/pollhub/adapter/controller/VoteController.java
=> ♻️Refactor: swagger controller 태그를 도메인 명으로 변경

src/main/java/com/startoy/pollhub/adapter/controller/PollController.java, src/main/java/com/startoy/pollhub/adapter/controller/PollOptionController.java, src/main/java/com/startoy/pollhub/adapter/controller/PostController.java, src/main/java/com/startoy/pollhub/adapter/controller/VoteController.java
=> 🧵Chore: 공통 api 주소 v1 -> api/v1 수정

src/main/java/com/startoy/pollhub/adapter/controller/FileStorageController.java, src/main/java/com/startoy/pollhub/adapter/controller/PollController.java, src/main/java/com/startoy/pollhub/adapter/controller/PollOptionController.java, src/main/java/com/startoy/pollhub/adapter/controller/PostController.java, src/main/java/com/startoy/pollhub/adapter/controller/VoteController.java, src/main/java/com/startoy/pollhub/config/SecurityConfig.java
=> 🐛Fix: API 공통 주소 api/v1 -> v1 변경

src/main/java/world/startoy/polling/domain/FileStorage.java, src/main/java/world/startoy/polling/domain/Poll.java, src/main/java/world/startoy/polling/domain/PollOption.java, src/main/java/world/startoy/polling/domain/Post.java, src/main/java/world/startoy/polling/domain/Vote.java, src/main/java/world/startoy/polling/usecase/FileStorageService.java, src/main/java/world/startoy/polling/usecase/PollOptionService.java, src/main/java/world/startoy/polling/usecase/PollService.java, src/main/java/world/startoy/polling/usecase/PostService.java, src/main/java/world/startoy/polling/usecase/VoteService.java
- pollhub ph -> polling pl
- unique uid 추가
- option -> poll option
- poll, poll_option sequence 추가
=> ✨ Feat: 테이블 스키마 변경에 따라 도메인 코드 수정

build.gradle, src/main/resources/application.properties
- tasks.named('test') {
useJUnitPlatform()
} 내용을 
test {
useJUnitPlatform()
} 로 수정
=> 🐛 Fix : build.gradle - useJUnitPlatform 수정

build.gradle, src/main/resources/application.properties, src/test/java/world/startoy/polling/PollingApplicationTests.java
test/java/world.startoy.polling 의 contextLoads() 테스트 코드 삭제
=> 🐛 Fix: test 코드 삭제 

.github/workflows/Java Backend CICD with Gradle.yml, build.gradle, src/main/java/world/startoy/polling/usecase/FileStorageService.java, src/main/resources/application.properties
-  build.gradle 에 jar 설정 추가
- application.properties 운영 DB 정보 주석처리
=> 🐛 Fix: build.gradle 에 jar 설정 추가

build.gradle, src/main/java/world/startoy/polling/adapter/controller/VoteController.java, src/main/java/world/startoy/polling/adapter/repository/VoteRepository.java, src/main/java/world/startoy/polling/domain/PollOption.java, src/main/java/world/startoy/polling/usecase/VoteService.java, src/main/java/world/startoy/polling/usecase/dto/OptionVoteRateDTO.java, src/main/java/world/startoy/polling/usecase/dto/VoteDTO.java, src/main/resources/application.properties
Chore: 서버내 jar 파일 교체를 위한 pr-commit
- 서버 내 jar 파일 교체를 위한 pr 및 commit 진행 건입니다.
=> Chore: 서버내 jar 파일 교체를 위한 pr-commit

src/main/java/world/startoy/polling/domain/Poll.java, src/main/java/world/startoy/polling/domain/PollOption.java
=> ✨ Feat: seq null 불가 자료형 Integer -> int 수정

src/main/java/world/startoy/polling/adapter/controller/PostController.java, src/main/java/world/startoy/polling/adapter/repository/PostRepository.java, src/main/java/world/startoy/polling/usecase/PostService.java, src/main/java/world/startoy/polling/usecase/dto/PostDTO.java, src/main/java/world/startoy/polling/usecase/dto/PostListResponse.java
- POST DTO를 사용하여 필요한 컬럼값만 api 로 가져올 수 있도록 수정.
+ 피곤하실텐데 늦은 밤까지 코드 설명해 주신 한날님과 세은님께 무한한 감사를 드립니다..
=> Feat : 홈화면 내 게시글 전체 리스트 조회시 DTO 사용하도록 수정

src/main/java/world/startoy/polling/config/WebMvcConfig.java
Fix : WebMvcConfig - allowedOrigins 수정
- https://localhost/*  삭제
=> Fix : WebMvcConfig - allowedOrigins 수정

src/main/java/world/startoy/polling/config/CloudFrontConfig.java, src/main/java/world/startoy/polling/config/S3Config.java, src/main/java/world/startoy/polling/config/SecurityConfig.java, src/main/java/world/startoy/polling/config/SwaggerConfig.java, src/main/java/world/startoy/polling/usecase/S3Service.java, src/main/resources/application.properties
=> fix : swagger servers list 수정

src/main/resources/application.properties
=> Fix/application properties modify - 포트 번호 변경

src/main/java/world/startoy/polling/adapter/controller/PostController.java, src/main/java/world/startoy/polling/adapter/repository/PostRepository.java, src/main/java/world/startoy/polling/domain/Post.java, src/main/java/world/startoy/polling/usecase/PostService.java, src/main/java/world/startoy/polling/usecase/dto/PostDTO.java
=> Feat: 게시글 전체 조회 API 추가

.gitignore, src/main/java/world/startoy/polling/adapter/controller/FileStorageController.java, src/main/java/world/startoy/polling/domain/PollOption.java, src/main/java/world/startoy/polling/domain/Post.java, src/main/java/world/startoy/polling/usecase/FileStorageService.java, src/main/java/world/startoy/polling/usecase/PostService.java, src/main/java/world/startoy/polling/usecase/VoteService.java, src/main/java/world/startoy/polling/usecase/dto/FileStorageDTO.java, src/main/java/world/startoy/polling/usecase/dto/PollOptionCreateRequest.java, src/main/java/world/startoy/polling/usecase/dto/PollOptionResponse.java, src/main/java/world/startoy/polling/usecase/dto/PostCreateRequest.java, src/main/java/world/startoy/polling/usecase/dto/PostDetailResponse.java
=> Fix: 게시글 작성시 파일 업로드 기능 추가

src/main/java/world/startoy/polling/adapter/controller/PostController.java, src/main/java/world/startoy/polling/adapter/repository/PostRepository.java, src/main/java/world/startoy/polling/adapter/repository/VoteRepository.java, src/main/java/world/startoy/polling/usecase/PostService.java, src/main/java/world/startoy/polling/usecase/VoteService.java, src/main/java/world/startoy/polling/usecase/dto/PollOptionResponse.java, src/main/java/world/startoy/polling/usecase/dto/PostDetailResponse.java
=> Feat: 게시글 상세 조회 시 파일 정보 추가 조회하도록 수정

src/main/java/world/startoy/polling/usecase/dto/PollOptionResponse.java, src/main/java/world/startoy/polling/usecase/dto/PostDetailResponse.java
#Fix/PostDetailResponse, PollOptionResponse 수정
- NotNull 어노테이션 추가
=> Fix/PostDetailResponse, PollOptionResponse 수정

src/main/java/world/startoy/polling/config/WebMvcConfig.java
#fix: WebMvcConfig addCors 수정
- "https://www.polling.world" 추가
=> fix: WebMvcConfig addCors 수정

src/main/java/world/startoy/polling/adapter/repository/VoteRepository.java, src/main/java/world/startoy/polling/usecase/PostService.java, src/main/java/world/startoy/polling/usecase/VoteService.java, src/main/java/world/startoy/polling/usecase/dto/PollOptionResponse.java
=> Fix: 게시글 상세 조회 시 옵션 정보 조회 오류 수정

src/main/java/world/startoy/polling/adapter/controller/FileStorageController.java, src/main/java/world/startoy/polling/adapter/controller/PollController.java, src/main/java/world/startoy/polling/adapter/controller/PollOptionController.java, src/main/java/world/startoy/polling/adapter/controller/PostController.java, src/main/java/world/startoy/polling/adapter/controller/VoteController.java
- API Tag name, description 수정
- api Operation summary 추가 및 수정
=> Feat: 불필요 api 삭제

src/main/java/world/startoy/polling/usecase/dto/FileStorageDTO.java
FileStorageDTO @NotNull 추가
file_full_name -> file_name 컬럼명 수정
=> Feat: FileStorageDTO 수정

src/main/java/world/startoy/polling/adapter/repository/PostRepository.java, src/main/java/world/startoy/polling/adapter/repository/VoteRepository.java, src/main/java/world/startoy/polling/domain/FileStorage.java, src/main/java/world/startoy/polling/usecase/FileStorageService.java, src/main/java/world/startoy/polling/usecase/PostService.java, src/main/java/world/startoy/polling/usecase/dto/FileStorageDTO.java, src/main/java/world/startoy/polling/usecase/dto/PollOptionResponse.java, src/main/java/world/startoy/polling/usecase/dto/PostDTO.java, src/main/java/world/startoy/polling/usecase/dto/PostDetailResponse.java
Feat: fileFullName -> fileName, file_full_name -> file_name
=> Feat: fileFullName -> fileName, file_full_name -> file_name

src/main/java/world/startoy/polling/adapter/repository/PostRepository.java, src/main/java/world/startoy/polling/usecase/PostService.java, src/main/java/world/startoy/polling/usecase/dto/PostDTO.java, src/main/java/world/startoy/polling/usecase/dto/PostDetailResponse.java
=> Fix/image url추가

src/main/java/world/startoy/polling/usecase/dto/PostDTO.java, src/main/java/world/startoy/polling/usecase/dto/PostDetailResponse.java
#Fix/notnull 어노테이션 추가
- PostDTO
- PostDetailResponse
=> Fix/notnull 어노테이션 추가

src/main/java/world/startoy/polling/adapter/repository/VoteRepository.java, src/main/java/world/startoy/polling/usecase/VoteService.java, src/main/java/world/startoy/polling/usecase/dto/PollOptionResponse.java
=> Fix: PollOptionResponse수정

src/main/java/world/startoy/polling/config/WebMvcConfig.java
#fix: WebMvcConfig - preview url 추가
=> fix: WebMvcConfig - preview url 추가

src/main/java/world/startoy/polling/adapter/controller/PostController.java, src/main/java/world/startoy/polling/config/CloudFrontConfig.java, src/main/java/world/startoy/polling/usecase/PostService.java, src/main/java/world/startoy/polling/usecase/UserService.java, src/main/java/world/startoy/polling/usecase/dto/PollOptionResponse.java
=> Feat: 게시글 상세 조회 시 사용자 투표 옵션 추가 조회하도록 수정

src/main/java/world/startoy/polling/config/WebMvcConfig.java
#fix: WebMvcConfig- https://api-dev.polling.world 추가
=> fix: WebMvcConfig- https://api-dev.polling.world 추가

src/main/java/world/startoy/polling/usecase/PostService.java
=> fix: PostService- 쿼리문 수정

.github/workflows/develop.yml, src/main/java/world/startoy/polling/config/WebMvcConfig.java, src/main/java/world/startoy/polling/usecase/PostService.java, src/main/resources/application.properties
#Fix/개발서버 배포 및 CORS 설정, 환경변수, 이미지오류 수정
=> Fix/개발서버 배포 및 CORS 설정, 환경변수, 이미지오류 수정

src/main/java/world/startoy/polling/adapter/controller/VoteController.java, src/main/java/world/startoy/polling/adapter/repository/VoteRepository.java, src/main/java/world/startoy/polling/usecase/VoteService.java
#Feature/delete vote api개발
deleteMapping - voteUid 파라미터 값으로 삭제
=> Feature/delete vote api개발

.github/workflows/develop.yml, src/main/java/world/startoy/polling/config/WebMvcConfig.java, src/main/resources/application.properties
=> feature/투표취소 api 개발

src/main/java/world/startoy/polling/usecase/PostService.java
#Feat: PostService - findPostDetailResponseByPostUid sql 수정, builder - sorted 추가
=> Feat: PostService - findPostDetailResponseByPostUid sql 수정, builder - sorted 추가
